package com.sc.pro.api.modelname.vo;

import java.io.Serializable;
import java.util.Date;

public class ArchUserVO implements Serializable  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.USER_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.PASSWORD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.PRIORITY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Long priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.IDENTITY_CARD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.GENDER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.BIRTHDAY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.DWELLING_PLACE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String dwellingPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.POSTALCODE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.TELEPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.EMAIL
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.MOBILE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.FAX_NO
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String faxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.SPOUSE_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String spouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.OA_ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String oaAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.USER_DESC
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String userDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.PROVIDER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String providerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.FLAG
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.FULLNAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.OPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String ophone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.FAX
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.OTHER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CANSENDSMS
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Long cansendsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.LANGUAGE_
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.LAST_UPDATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date lastUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CREATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT03
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT04
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT05
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT06
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT07
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT08
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_TEXT09
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String custText09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_NUMBER01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Long custNumber01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_NUMBER02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Long custNumber02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_DATE01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date custDate01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.CUST_DATE02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date custDate02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.QQ
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.MSN
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.SOURCE_SYSTEM
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String sourceSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.SOURCE_SYSTEM_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String sourceSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.SOURCE_SYSTEM_LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String sourceSystemLastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.ORG_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.USER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.EXPIRATION_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arch_user.LOGIN_COUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    private Long loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.USER_ID
     *
     * @return the value of arch_user.USER_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.USER_ID
     *
     * @param userId the value for arch_user.USER_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.ACCOUNT
     *
     * @return the value of arch_user.ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.ACCOUNT
     *
     * @param account the value for arch_user.ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.PASSWORD
     *
     * @return the value of arch_user.PASSWORD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.PASSWORD
     *
     * @param password the value for arch_user.PASSWORD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.PRIORITY
     *
     * @return the value of arch_user.PRIORITY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.PRIORITY
     *
     * @param priority the value for arch_user.PRIORITY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.IDENTITY_CARD
     *
     * @return the value of arch_user.IDENTITY_CARD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.IDENTITY_CARD
     *
     * @param identityCard the value for arch_user.IDENTITY_CARD
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.GENDER
     *
     * @return the value of arch_user.GENDER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.GENDER
     *
     * @param gender the value for arch_user.GENDER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.BIRTHDAY
     *
     * @return the value of arch_user.BIRTHDAY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.BIRTHDAY
     *
     * @param birthday the value for arch_user.BIRTHDAY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.DWELLING_PLACE
     *
     * @return the value of arch_user.DWELLING_PLACE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getDwellingPlace() {
        return dwellingPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.DWELLING_PLACE
     *
     * @param dwellingPlace the value for arch_user.DWELLING_PLACE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setDwellingPlace(String dwellingPlace) {
        this.dwellingPlace = dwellingPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.POSTALCODE
     *
     * @return the value of arch_user.POSTALCODE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.POSTALCODE
     *
     * @param postalcode the value for arch_user.POSTALCODE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.TELEPHONE
     *
     * @return the value of arch_user.TELEPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.TELEPHONE
     *
     * @param telephone the value for arch_user.TELEPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.EMAIL
     *
     * @return the value of arch_user.EMAIL
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.EMAIL
     *
     * @param email the value for arch_user.EMAIL
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.MOBILE
     *
     * @return the value of arch_user.MOBILE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.MOBILE
     *
     * @param mobile the value for arch_user.MOBILE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.FAX_NO
     *
     * @return the value of arch_user.FAX_NO
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getFaxNo() {
        return faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.FAX_NO
     *
     * @param faxNo the value for arch_user.FAX_NO
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.SPOUSE_NAME
     *
     * @return the value of arch_user.SPOUSE_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getSpouseName() {
        return spouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.SPOUSE_NAME
     *
     * @param spouseName the value for arch_user.SPOUSE_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.OA_ACCOUNT
     *
     * @return the value of arch_user.OA_ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getOaAccount() {
        return oaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.OA_ACCOUNT
     *
     * @param oaAccount the value for arch_user.OA_ACCOUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setOaAccount(String oaAccount) {
        this.oaAccount = oaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.USER_DESC
     *
     * @return the value of arch_user.USER_DESC
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.USER_DESC
     *
     * @param userDesc the value for arch_user.USER_DESC
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.PROVIDER_NAME
     *
     * @return the value of arch_user.PROVIDER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.PROVIDER_NAME
     *
     * @param providerName the value for arch_user.PROVIDER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.FLAG
     *
     * @return the value of arch_user.FLAG
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.FLAG
     *
     * @param flag the value for arch_user.FLAG
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.FULLNAME
     *
     * @return the value of arch_user.FULLNAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.FULLNAME
     *
     * @param fullname the value for arch_user.FULLNAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.OPHONE
     *
     * @return the value of arch_user.OPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getOphone() {
        return ophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.OPHONE
     *
     * @param ophone the value for arch_user.OPHONE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setOphone(String ophone) {
        this.ophone = ophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.FAX
     *
     * @return the value of arch_user.FAX
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.FAX
     *
     * @param fax the value for arch_user.FAX
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.OTHER
     *
     * @return the value of arch_user.OTHER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.OTHER
     *
     * @param other the value for arch_user.OTHER
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CANSENDSMS
     *
     * @return the value of arch_user.CANSENDSMS
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Long getCansendsms() {
        return cansendsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CANSENDSMS
     *
     * @param cansendsms the value for arch_user.CANSENDSMS
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCansendsms(Long cansendsms) {
        this.cansendsms = cansendsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.LANGUAGE_
     *
     * @return the value of arch_user.LANGUAGE_
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.LANGUAGE_
     *
     * @param language the value for arch_user.LANGUAGE_
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.LAST_UPDATED_BY
     *
     * @return the value of arch_user.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for arch_user.LAST_UPDATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.LAST_UPDATED_DATE
     *
     * @return the value of arch_user.LAST_UPDATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for arch_user.LAST_UPDATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CREATED_BY
     *
     * @return the value of arch_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CREATED_BY
     *
     * @param createdBy the value for arch_user.CREATED_BY
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CREATED_DATE
     *
     * @return the value of arch_user.CREATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CREATED_DATE
     *
     * @param createdDate the value for arch_user.CREATED_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT01
     *
     * @return the value of arch_user.CUST_TEXT01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText01() {
        return custText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT01
     *
     * @param custText01 the value for arch_user.CUST_TEXT01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText01(String custText01) {
        this.custText01 = custText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT02
     *
     * @return the value of arch_user.CUST_TEXT02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText02() {
        return custText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT02
     *
     * @param custText02 the value for arch_user.CUST_TEXT02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText02(String custText02) {
        this.custText02 = custText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT03
     *
     * @return the value of arch_user.CUST_TEXT03
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText03() {
        return custText03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT03
     *
     * @param custText03 the value for arch_user.CUST_TEXT03
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText03(String custText03) {
        this.custText03 = custText03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT04
     *
     * @return the value of arch_user.CUST_TEXT04
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText04() {
        return custText04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT04
     *
     * @param custText04 the value for arch_user.CUST_TEXT04
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText04(String custText04) {
        this.custText04 = custText04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT05
     *
     * @return the value of arch_user.CUST_TEXT05
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText05() {
        return custText05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT05
     *
     * @param custText05 the value for arch_user.CUST_TEXT05
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText05(String custText05) {
        this.custText05 = custText05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT06
     *
     * @return the value of arch_user.CUST_TEXT06
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText06() {
        return custText06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT06
     *
     * @param custText06 the value for arch_user.CUST_TEXT06
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText06(String custText06) {
        this.custText06 = custText06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT07
     *
     * @return the value of arch_user.CUST_TEXT07
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText07() {
        return custText07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT07
     *
     * @param custText07 the value for arch_user.CUST_TEXT07
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText07(String custText07) {
        this.custText07 = custText07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT08
     *
     * @return the value of arch_user.CUST_TEXT08
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText08() {
        return custText08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT08
     *
     * @param custText08 the value for arch_user.CUST_TEXT08
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText08(String custText08) {
        this.custText08 = custText08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_TEXT09
     *
     * @return the value of arch_user.CUST_TEXT09
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getCustText09() {
        return custText09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_TEXT09
     *
     * @param custText09 the value for arch_user.CUST_TEXT09
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustText09(String custText09) {
        this.custText09 = custText09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_NUMBER01
     *
     * @return the value of arch_user.CUST_NUMBER01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Long getCustNumber01() {
        return custNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_NUMBER01
     *
     * @param custNumber01 the value for arch_user.CUST_NUMBER01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustNumber01(Long custNumber01) {
        this.custNumber01 = custNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_NUMBER02
     *
     * @return the value of arch_user.CUST_NUMBER02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Long getCustNumber02() {
        return custNumber02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_NUMBER02
     *
     * @param custNumber02 the value for arch_user.CUST_NUMBER02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustNumber02(Long custNumber02) {
        this.custNumber02 = custNumber02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_DATE01
     *
     * @return the value of arch_user.CUST_DATE01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getCustDate01() {
        return custDate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_DATE01
     *
     * @param custDate01 the value for arch_user.CUST_DATE01
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustDate01(Date custDate01) {
        this.custDate01 = custDate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.CUST_DATE02
     *
     * @return the value of arch_user.CUST_DATE02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getCustDate02() {
        return custDate02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.CUST_DATE02
     *
     * @param custDate02 the value for arch_user.CUST_DATE02
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setCustDate02(Date custDate02) {
        this.custDate02 = custDate02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.QQ
     *
     * @return the value of arch_user.QQ
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.QQ
     *
     * @param qq the value for arch_user.QQ
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.MSN
     *
     * @return the value of arch_user.MSN
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.MSN
     *
     * @param msn the value for arch_user.MSN
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setMsn(String msn) {
        this.msn = msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.SOURCE_SYSTEM
     *
     * @return the value of arch_user.SOURCE_SYSTEM
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.SOURCE_SYSTEM
     *
     * @param sourceSystem the value for arch_user.SOURCE_SYSTEM
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setSourceSystem(String sourceSystem) {
        this.sourceSystem = sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.SOURCE_SYSTEM_ID
     *
     * @return the value of arch_user.SOURCE_SYSTEM_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getSourceSystemId() {
        return sourceSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.SOURCE_SYSTEM_ID
     *
     * @param sourceSystemId the value for arch_user.SOURCE_SYSTEM_ID
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setSourceSystemId(String sourceSystemId) {
        this.sourceSystemId = sourceSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.SOURCE_SYSTEM_LAST_UPDATE_DATE
     *
     * @return the value of arch_user.SOURCE_SYSTEM_LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getSourceSystemLastUpdateDate() {
        return sourceSystemLastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.SOURCE_SYSTEM_LAST_UPDATE_DATE
     *
     * @param sourceSystemLastUpdateDate the value for arch_user.SOURCE_SYSTEM_LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setSourceSystemLastUpdateDate(String sourceSystemLastUpdateDate) {
        this.sourceSystemLastUpdateDate = sourceSystemLastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.ORG_NAME
     *
     * @return the value of arch_user.ORG_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.ORG_NAME
     *
     * @param orgName the value for arch_user.ORG_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.USER_NAME
     *
     * @return the value of arch_user.USER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.USER_NAME
     *
     * @param userName the value for arch_user.USER_NAME
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.EXPIRATION_DATE
     *
     * @return the value of arch_user.EXPIRATION_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.EXPIRATION_DATE
     *
     * @param expirationDate the value for arch_user.EXPIRATION_DATE
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arch_user.LOGIN_COUNT
     *
     * @return the value of arch_user.LOGIN_COUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arch_user.LOGIN_COUNT
     *
     * @param loginCount the value for arch_user.LOGIN_COUNT
     *
     * @mbggenerated Tue Aug 11 16:01:54 CST 2015
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }
}